import { Card, CardContent } from "@/components/ui/card"
import { NotebookIcon as Lotus, Heart, Sparkles, Leaf } from "lucide-react"

export default function AboutSection() {
  const features = [
    {
      icon: Lotus,
      title: "Strength Training",
      description: "Modern strength and conditioning workouts for all levels.",
    },
    {
      icon: Sparkles,
      title: "AI-Powered Plans",
      description: "Personalized wellness and diet plans generated by advanced AI technology.",
    },
    {
      icon: Heart,
      title: "Holistic Healing",
      description: "Complete mind-body wellness through meditation, pranayama, and Ayurvedic principles.",
    },
    {
      icon: Leaf,
      title: "Natural Approach",
      description: "Embrace natural healing methods and organic lifestyle practices for optimal health.",
    },
  ]

  return (
    <section className="py-20 bg-gradient-to-b from-green-50 to-white dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 fitness-text-gradient">About Ultima Fitness Gym</h2>
          <p className="text-lg text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
            We blend ancient Indian wisdom with modern technology to create a unique wellness experience. Our studio is
            a sanctuary where tradition meets innovation, offering personalized paths to health and happiness.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
          {features.map((feature, index) => (
            <Card key={index} className="text-center hover:shadow-lg transition-shadow duration-300">
              <CardContent className="p-6">
                <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 dark:bg-green-900 rounded-full mb-4">
                  <feature.icon className="h-8 w-8 text-green-600 dark:text-green-400" />
                </div>
                <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-gray-600 dark:text-gray-300">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div>
            <h3 className="text-2xl md:text-3xl font-bold mb-6">Your Journey to Wellness Starts Here</h3>
            <div className="space-y-4">
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-600 dark:text-gray-300">
                  <strong>Personalized Approach:</strong> Every student receives customized guidance based on their
                  unique needs and goals.
                </p>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-600 dark:text-gray-300">
                  <strong>Expert Guidance:</strong> Learn from certified yoga instructors with deep knowledge of
                  traditional practices.
                </p>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-600 dark:text-gray-300">
                  <strong>Modern Technology:</strong> Leverage AI-powered wellness plans and digital tools for optimal
                  results.
                </p>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-600 dark:text-gray-300">
                  <strong>Community Support:</strong> Join a supportive community of like-minded individuals on their
                  wellness journey.
                </p>
              </div>
            </div>
          </div>
          <div className="relative">
            <img
              src="/placeholder.svg?height=400&width=600"
              alt="Yoga practice"
              className="rounded-lg shadow-lg w-full"
            />
            <div className="absolute -bottom-4 -right-4 bg-white dark:bg-gray-800 p-4 rounded-lg shadow-lg">
              <div className="text-2xl font-bold text-green-600">4.9/5</div>
              <div className="text-sm text-gray-600 dark:text-gray-300">Student Rating</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
